# Generated by Django 6.0.4 on 2026-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('precio_venta', models.FloatField()),
                ('ingreso_total', models.FloatField()),
                ('costo_produccion', models.FloatField()),
                ('ganancia', models.FloatField()),
                ('vendedor', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
